apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsog
  namespace: rso
  labels:
    app: rsog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rsog
  template:
    metadata:
      labels:
        app: rsog
    spec:
      containers:
      - name: rsog
        image: matejbrodnik/rsog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4001
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: azure-sql-credentials
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: azure-sql-credentials
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: azure-sql-credentials
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: azure-sql-credentials
              key: db-name
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rsogs
  namespace: rso
spec:
  selector:
    app: rsog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001