apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsoa
  labels:
    app: rsoa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rsoa
  template:
    metadata:
      labels:
        app: rsoa
    spec:
      containers:
      - name: rsoa
        image: matejbrodnik/rsoa:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: azure-sql-credentials
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: azure-sql-credentials
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: azure-sql-credentials
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: azure-sql-credentials
              key: db-name
      imagePullSecrets:
      - name: dockerhub-secret
