apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rsoa-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: rsoa
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - rso