DROP TABLE IF EXISTS Locations
DROP TABLE IF EXISTS Users

CREATE TABLE Users (
   id INT PRIMARY KEY IDENTITY(1,1),
   username NVARCHAR(50) NOT NULL,
   password NVARCHAR(255) NOT NULL
);

CREATE TABLE Locations (
    id INT PRIMARY KEY IDENTITY(1,1),
    uid INT,
    lat FLOAT,
    lng FLOAT,
	CONSTRAINT fk_uid FOREIGN KEY (uid) REFERENCES Users(id)
);
