name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - rso
          - server/auth
          - server/geo
        image:
          - rsof
          - rsoa
          - rsog

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build/push Image
        run: |
          cd ${{ matrix.directory }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:${{ github.sha }} .
          docker tag ${{ matrix.image }} matejbrodnik/${{ matrix.image }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:latest
