name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build/push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsof:${{ github.sha }} .
          docker tag rsof matejbrodnik/rsof:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rsof:latest

          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsoa:${{ github.sha }} .
          docker tag rsoa matejbrodnik/rsoa:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rsoa:latest

          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsog:${{ github.sha }} .
          docker tag rsog matejbrodnik/rsog:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rsog:latest

