name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     directory:
    #       - rso
    #       - server/auth
    #       - server/geo
    #     image:
    #       - rsof
    #       - rsoa
    #       - rsog

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build/push rsof
        run: |
          cd rso
          npm install
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsof:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/rsof:latest
      
      - name: Build/push rsoa
        run: |
          cd server/auth
          npm install
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsoa:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/rsoa:latest

      - name: Build/push rsog
        run: |
          cd server/geo
          npm install
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rsog:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/rsog:latest
      
      - name: Set up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Access check
        run: kubectl get nodes

      - name: Reset cluster
        run: |
          kubectl rollout restart --namespace rso
